#include "language.hpp"
#include "detector.hpp"
#include "counter.hpp"
#include "walker.hpp"
#include "formatter.hpp"
#include "cocomo.hpp"
#include <cstdio>
#include <cstring>
#include <thread>
#include <vector>
#include <algorithm>
#include <atomic>
#include <fstream>
#include <sstream>

/* ---- Remap helpers ---- */

struct RemapRule { std::string pattern; std::string language; };

static std::vector<RemapRule> parseRemapRules(const std::string& value) {
    std::vector<RemapRule> rules;
    if (value.empty()) return rules;
    size_t pos = 0;
    while (pos < value.size()) {
        size_t comma = value.find(',', pos);
        std::string pair = (comma == std::string::npos) ? value.substr(pos) : value.substr(pos, comma - pos);
        pos = (comma == std::string::npos) ? value.size() : comma + 1;
        size_t colon = pair.find(':');
        if (colon != std::string::npos) {
            rules.push_back({pair.substr(0, colon), pair.substr(colon + 1)});
        }
    }
    return rules;
}

/* ---- Flags (matching scc CLI) ---- */
static bool flagLanguages = false;
static bool flagByFile = false;
static bool flagNoComplexity = false;
static bool flagMore = false;
static bool flagCi = false;
static bool flagIncludeSymLinks = false;
static bool flagNoLarge = false;
static int64_t flagLargeLineCount = 40000;
static int64_t flagLargeByteCount = 1000000;
static std::string flagSortBy = "files";
static std::string flagFormat = "tabular";
static std::string flagAllowExt;
static std::string flagExcludeExt;
static std::string flagExcludeFile;
static std::string flagOutput;
static int flagWorkers = 0;
static std::string flagCountAs;
static std::string flagRemapAll;
static std::string flagRemapUnknown;
static std::string flagFormatMulti;
static bool flagNoGitignore = false;
static bool flagNoIgnore = false;
static bool flagNoSccIgnore = false;
static bool flagNoGitmodule = false;
static bool flagCountIgnore = false;
static bool flagMinifiedGenerated = false;
static bool flagMinified = false;
static bool flagGenerated = false;
static bool flagIgnoreMinGen = false;
static bool flagIgnoreMinified = false;
static bool flagIgnoreGenerated = false;
static std::string flagGeneratedMarkers = "do not edit,<auto-generated />";
static int flagMinGenLineLength = 255;
static bool flagNoDuplicates = false;
static bool flagUloc = false;
static bool flagDryness = false;
static bool flagPercent = false;
static bool flagMaxMean = false;
static bool flagNoHborder = false;
static bool flagDisableCheckBinary = false;
static bool flagNoCocomo = false;
static bool flagSloccountFormat = false;
static std::string flagCocomoProjectType = "organic";
static int64_t flagAverageWage = 56286;
static double flagOverhead = 2.4;
static double flagEAF = 1.0;
static std::string flagCurrencySymbol = "$";
static bool flagLocomo = false;
static bool flagCostComparison = false;
static std::string flagLocomoPreset = "medium";
static double flagLocomoInputPrice = 0;
static double flagLocomoOutputPrice = 0;
static double flagLocomoTPS = 0;
static bool flagLocomoInputPriceSet = false;
static bool flagLocomoOutputPriceSet = false;
static bool flagLocomoTPSSet = false;
static double flagLocomoCycles = 0;
static bool flagLocomoCyclesSet = false;
static std::string flagSizeUnit = "si";
static bool flagNoSize = false;
static std::string flagSQLProject;

static void printUsage(const char* prog) {
    fprintf(stderr,
        "sccpp - Sloc Cloc and Code (pure C++ port of scc)\n"
        "Usage: %s [flags] [files or directories...]\n\n"
        "Flags:\n"
        "  -f, --format FMT     Output format [tabular, wide, json, json2, csv, csv-stream, cloc-yaml]\n"
        "  -l, --languages      Print supported languages and exit\n"
        "  -c, --no-complexity  Skip complexity calculation\n"
        "  -w, --wide           Wider output\n"
        "  --by-file            Show per-file output\n"
        "  --ci                 ASCII-safe output for CI\n"
        "  --include-symlinks   Count symlinked files\n"
        "  --no-large           Skip large files\n"
        "  --exclude-dir DIR    Directories to exclude (repeatable)\n"
        "  -i, --include-ext E  Limit to extensions (comma-sep)\n"
        "  -x, --exclude-ext E  Exclude extensions (comma-sep)\n"
        "  -n, --exclude-file F Exclude files by name (comma-sep)\n"
        "  -s, --sort COL       Sort by: files, lines, blanks, code, comments, complexity\n"
        "  -o, --output FILE    Write output to file\n"
        "  -j, --workers N      Number of worker threads (default: CPU count)\n"
        "  --count-as RULE      Count extension as language [e.g. jsp:htm]\n"
        "  --remap-all RULE     Remap any file by content pattern [e.g. \"-*- C++ -*-\":\"C Header\"]\n"
        "  --remap-unknown RULE Remap unknown files by content pattern\n"
        "  --no-gitignore       Disable .gitignore logic\n"
        "  --no-ignore          Disable .ignore file logic\n"
        "  --format-multi SPEC  Multiple outputs [e.g. tabular:stdout,json:file.json]\n"
        "  -h, --help           Show this help\n",
        prog);
}

static std::vector<std::string> splitCSV(const std::string& s) {
    std::vector<std::string> result;
    if (s.empty()) return result;
    size_t pos = 0;
    while (pos <= s.size()) {
        size_t comma = s.find(',', pos);
        std::string item = (comma == std::string::npos) ? s.substr(pos) : s.substr(pos, comma - pos);
        if (!item.empty()) result.push_back(item);
        if (comma == std::string::npos) break;
        pos = comma + 1;
    }
    return result;
}

/* Read a file from disk (for @flags.txt syntax) */
static std::string readTextFile(const std::string& path) {
    std::ifstream f(path);
    if (!f) return "";
    std::stringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

int main(int argc, char* argv[]) {
    std::vector<std::string> paths;
    std::vector<std::string> excludeDirs;

    /* Handle @flags.txt syntax */
    if (argc == 2 && argv[1][0] == '@') {
        std::string content = readTextFile(argv[1] + 1);
        if (content.empty()) { fprintf(stderr, "Cannot read flags file: %s\n", argv[1] + 1); return 1; }
        /* Tokenize by whitespace/newline */
        std::vector<std::string> newArgs;
        newArgs.push_back(argv[0]);
        std::istringstream iss(content);
        std::string tok;
        while (iss >> tok) newArgs.push_back(tok);
        /* Re-parse with new args */
        std::vector<char*> newArgv;
        for (auto& s : newArgs) newArgv.push_back(&s[0]);
        argc = (int)newArgv.size();
        /* Recurse — reuse argv allocation on stack */
        std::vector<std::string> storedArgs = newArgs;
        std::vector<char*> ptrs;
        ptrs.push_back(argv[0]); /* program name */
        for (size_t i = 1; i < storedArgs.size(); i++) ptrs.push_back(&storedArgs[i][0]);
        /* Reparse */
        paths.clear(); excludeDirs.clear();
        for (int i = 1; i < (int)ptrs.size(); i++) {
            std::string arg = ptrs[i];
            /* Re-parse all flags inline */
            if (arg == "-h" || arg == "--help") { printUsage(argv[0]); return 0; }
            else if (arg == "-l" || arg == "--languages") flagLanguages = true;
            else if (arg == "-c" || arg == "--no-complexity") flagNoComplexity = true;
            else if (arg == "-w" || arg == "--wide") flagMore = true;
            else if (arg == "--by-file") flagByFile = true;
            else if (arg == "--ci") flagCi = true;
            else if (arg == "--include-symlinks") flagIncludeSymLinks = true;
            else if (arg == "--no-large") flagNoLarge = true;
            else if (arg == "--no-gitignore") flagNoGitignore = true;
            else if (arg == "--no-ignore") flagNoIgnore = true;
        else if (arg == "--no-scc-ignore") flagNoSccIgnore = true;
        else if (arg == "--no-gitmodule") flagNoGitmodule = true;
        else if (arg == "--count-ignore") flagCountIgnore = true;
        else if (arg == "-z" || arg == "--min-gen") flagMinifiedGenerated = true;
        else if (arg == "--min") flagMinified = true;
        else if (arg == "--gen") flagGenerated = true;
        else if (arg == "--no-min-gen") flagIgnoreMinGen = true;
        else if (arg == "--no-min") flagIgnoreMinified = true;
        else if (arg == "--no-gen") flagIgnoreGenerated = true;
        else if (arg == "-d" || arg == "--no-duplicates") flagNoDuplicates = true;
        else if (arg == "-u" || arg == "--uloc") flagUloc = true;
        else if (arg == "-a" || arg == "--dryness") flagDryness = true;
        else if (arg == "-p" || arg == "--percent") flagPercent = true;
        else if (arg == "-m" || arg == "--character") flagMaxMean = true;
        else if (arg == "--no-hborder") flagNoHborder = true;
        else if (arg == "--binary") flagDisableCheckBinary = true;
        else if (arg == "--no-cocomo") flagNoCocomo = true;
        else if (arg == "--sloccount-format") flagSloccountFormat = true;
        else if (arg == "--no-size") flagNoSize = true;
        else if (arg == "--locomo") flagLocomo = true;
        else if (arg == "--cost-comparison") flagCostComparison = true;
        else if (arg == "--locomo-cycles" && i + 1 < argc) { flagLocomoCycles = std::atof(argv[++i]); flagLocomoCyclesSet = true; }
        else if (arg == "--locomo-preset" && i + 1 < argc) flagLocomoPreset = argv[++i];
        else if (arg == "--locomo-input-price" && i + 1 < argc) { flagLocomoInputPrice = std::atof(argv[++i]); flagLocomoInputPriceSet = true; }
        else if (arg == "--locomo-output-price" && i + 1 < argc) { flagLocomoOutputPrice = std::atof(argv[++i]); flagLocomoOutputPriceSet = true; }
        else if (arg == "--locomo-tps" && i + 1 < argc) { flagLocomoTPS = std::atof(argv[++i]); flagLocomoTPSSet = true; }
        else if (arg == "--avg-wage" && i + 1 < argc) flagAverageWage = std::atoll(argv[++i]);
        else if (arg == "--overhead" && i + 1 < argc) flagOverhead = std::atof(argv[++i]);
        else if (arg == "--eaf" && i + 1 < argc) flagEAF = std::atof(argv[++i]);
        else if (arg == "--cocomo-project-type" && i + 1 < argc) flagCocomoProjectType = argv[++i];
        else if (arg == "--currency-symbol" && i + 1 < argc) flagCurrencySymbol = argv[++i];
        else if (arg == "--size-unit" && i + 1 < argc) flagSizeUnit = argv[++i];
        else if (arg == "--sql-project" && i + 1 < argc) flagSQLProject = argv[++i];
        else if (arg == "--min-gen-line-length" && i + 1 < argc) flagMinGenLineLength = std::atoi(argv[++i]);
        else if (arg == "--large-line-count" && i + 1 < argc) flagLargeLineCount = std::atoll(argv[++i]);
        else if (arg == "--large-byte-count" && i + 1 < argc) flagLargeByteCount = std::atoll(argv[++i]);
        else if (arg == "--generated-markers" && i + 1 < argc) flagGeneratedMarkers = argv[++i];
            else if ((arg == "-f" || arg == "--format") && i + 1 < argc) flagFormat = ptrs[++i];
            else if ((arg == "-s" || arg == "--sort") && i + 1 < argc) flagSortBy = ptrs[++i];
            else if ((arg == "-i" || arg == "--include-ext") && i + 1 < argc) flagAllowExt = ptrs[++i];
            else if ((arg == "-x" || arg == "--exclude-ext") && i + 1 < argc) flagExcludeExt = ptrs[++i];
            else if ((arg == "-n" || arg == "--exclude-file") && i + 1 < argc) flagExcludeFile = ptrs[++i];
            else if ((arg == "-o" || arg == "--output") && i + 1 < argc) flagOutput = ptrs[++i];
            else if ((arg == "-j" || arg == "--workers") && i + 1 < argc) flagWorkers = std::atoi(ptrs[++i]);
            else if (arg == "--count-as" && i + 1 < argc) flagCountAs = ptrs[++i];
            else if (arg == "--remap-all" && i + 1 < argc) flagRemapAll = ptrs[++i];
            else if (arg == "--remap-unknown" && i + 1 < argc) flagRemapUnknown = ptrs[++i];
            else if (arg == "--format-multi" && i + 1 < argc) flagFormatMulti = ptrs[++i];
            else if (arg == "--exclude-dir" && i + 1 < argc) excludeDirs.push_back(ptrs[++i]);
            else if (arg[0] != '-') paths.push_back(arg);
            else { fprintf(stderr, "Unknown flag: %s\n", arg.c_str()); return 1; }
        }
        goto skip_parse;
    }

    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg == "-h" || arg == "--help") { printUsage(argv[0]); return 0; }
        else if (arg == "-l" || arg == "--languages") flagLanguages = true;
        else if (arg == "-c" || arg == "--no-complexity") flagNoComplexity = true;
        else if (arg == "-w" || arg == "--wide") flagMore = true;
        else if (arg == "--by-file") flagByFile = true;
        else if (arg == "--ci") flagCi = true;
        else if (arg == "--include-symlinks") flagIncludeSymLinks = true;
        else if (arg == "--no-large") flagNoLarge = true;
        else if (arg == "--no-gitignore") flagNoGitignore = true;
        else if (arg == "--no-ignore") flagNoIgnore = true;
        else if (arg == "--no-scc-ignore") flagNoSccIgnore = true;
        else if (arg == "--no-gitmodule") flagNoGitmodule = true;
        else if (arg == "--count-ignore") flagCountIgnore = true;
        else if (arg == "-z" || arg == "--min-gen") flagMinifiedGenerated = true;
        else if (arg == "--min") flagMinified = true;
        else if (arg == "--gen") flagGenerated = true;
        else if (arg == "--no-min-gen") flagIgnoreMinGen = true;
        else if (arg == "--no-min") flagIgnoreMinified = true;
        else if (arg == "--no-gen") flagIgnoreGenerated = true;
        else if (arg == "-d" || arg == "--no-duplicates") flagNoDuplicates = true;
        else if (arg == "-u" || arg == "--uloc") flagUloc = true;
        else if (arg == "-a" || arg == "--dryness") flagDryness = true;
        else if (arg == "-p" || arg == "--percent") flagPercent = true;
        else if (arg == "-m" || arg == "--character") flagMaxMean = true;
        else if (arg == "--no-hborder") flagNoHborder = true;
        else if (arg == "--binary") flagDisableCheckBinary = true;
        else if (arg == "--no-cocomo") flagNoCocomo = true;
        else if (arg == "--sloccount-format") flagSloccountFormat = true;
        else if (arg == "--no-size") flagNoSize = true;
        else if (arg == "--locomo") flagLocomo = true;
        else if (arg == "--cost-comparison") flagCostComparison = true;
        else if (arg == "--locomo-cycles" && i + 1 < argc) { flagLocomoCycles = std::atof(argv[++i]); flagLocomoCyclesSet = true; }
        else if (arg == "--locomo-preset" && i + 1 < argc) flagLocomoPreset = argv[++i];
        else if (arg == "--locomo-input-price" && i + 1 < argc) { flagLocomoInputPrice = std::atof(argv[++i]); flagLocomoInputPriceSet = true; }
        else if (arg == "--locomo-output-price" && i + 1 < argc) { flagLocomoOutputPrice = std::atof(argv[++i]); flagLocomoOutputPriceSet = true; }
        else if (arg == "--locomo-tps" && i + 1 < argc) { flagLocomoTPS = std::atof(argv[++i]); flagLocomoTPSSet = true; }
        else if (arg == "--avg-wage" && i + 1 < argc) flagAverageWage = std::atoll(argv[++i]);
        else if (arg == "--overhead" && i + 1 < argc) flagOverhead = std::atof(argv[++i]);
        else if (arg == "--eaf" && i + 1 < argc) flagEAF = std::atof(argv[++i]);
        else if (arg == "--cocomo-project-type" && i + 1 < argc) flagCocomoProjectType = argv[++i];
        else if (arg == "--currency-symbol" && i + 1 < argc) flagCurrencySymbol = argv[++i];
        else if (arg == "--size-unit" && i + 1 < argc) flagSizeUnit = argv[++i];
        else if (arg == "--sql-project" && i + 1 < argc) flagSQLProject = argv[++i];
        else if (arg == "--min-gen-line-length" && i + 1 < argc) flagMinGenLineLength = std::atoi(argv[++i]);
        else if (arg == "--large-line-count" && i + 1 < argc) flagLargeLineCount = std::atoll(argv[++i]);
        else if (arg == "--large-byte-count" && i + 1 < argc) flagLargeByteCount = std::atoll(argv[++i]);
        else if (arg == "--generated-markers" && i + 1 < argc) flagGeneratedMarkers = argv[++i];
        else if ((arg == "-f" || arg == "--format") && i + 1 < argc) flagFormat = argv[++i];
        else if ((arg == "-s" || arg == "--sort") && i + 1 < argc) flagSortBy = argv[++i];
        else if ((arg == "-i" || arg == "--include-ext") && i + 1 < argc) flagAllowExt = argv[++i];
        else if ((arg == "-x" || arg == "--exclude-ext") && i + 1 < argc) flagExcludeExt = argv[++i];
        else if ((arg == "-n" || arg == "--exclude-file") && i + 1 < argc) flagExcludeFile = argv[++i];
        else if ((arg == "-o" || arg == "--output") && i + 1 < argc) flagOutput = argv[++i];
        else if ((arg == "-j" || arg == "--workers") && i + 1 < argc) flagWorkers = std::atoi(argv[++i]);
        else if (arg == "--count-as" && i + 1 < argc) flagCountAs = argv[++i];
        else if (arg == "--remap-all" && i + 1 < argc) flagRemapAll = argv[++i];
        else if (arg == "--remap-unknown" && i + 1 < argc) flagRemapUnknown = argv[++i];
        else if (arg == "--format-multi" && i + 1 < argc) flagFormatMulti = argv[++i];
        else if (arg == "--exclude-dir" && i + 1 < argc) excludeDirs.push_back(argv[++i]);
        else if (arg[0] != '-') paths.push_back(arg);
        else { fprintf(stderr, "Unknown flag: %s\n", arg.c_str()); return 1; }
    }

skip_parse:
    if (excludeDirs.empty()) excludeDirs = {".git", ".hg", ".svn"};

    /* Process flag implications (matching Go's processFlags) */
    if (flagMore && flagNoComplexity) flagNoComplexity = false;
    if (flagIgnoreMinGen) { flagMinifiedGenerated = true; flagIgnoreMinified = true; flagIgnoreGenerated = true; }
    if (flagMinifiedGenerated) { flagMinified = true; flagGenerated = true; }
    if (flagIgnoreMinified) flagMinified = true;
    if (flagIgnoreGenerated) flagGenerated = true;
    if (flagDryness) flagUloc = true;

    /* Parse custom COCOMO project type: "custom,a,b,c,d" */
    {
        std::string pt = flagCocomoProjectType;
        for (auto& c : pt) c = (char)std::tolower((unsigned char)c);
        if (cocomoProjectTypes.find(pt) == cocomoProjectTypes.end()) {
            /* Try to parse as custom */
            auto parts = splitCSV(pt);
            if (parts.size() == 5 && parts[0] == "custom") {
                std::vector<double> vals;
                for (int pi = 1; pi <= 4; pi++) {
                    vals.push_back(std::atof(parts[pi].c_str()));
                }
                if (vals.size() == 4) cocomoProjectTypes[pt] = vals;
            }
        }
    }

    /* Build CountOptions */
    CountOptions copts;
    copts.skipComplexity = flagNoComplexity;
    copts.checkMinified = flagMinified;
    copts.checkGenerated = flagGenerated;
    copts.checkBinary = !flagDisableCheckBinary;
    copts.minGenLineLength = flagMinGenLineLength;
    if (flagGenerated || flagMinifiedGenerated) {
        copts.generatedMarkers = splitCSV(flagGeneratedMarkers);
    }

    initLanguageDatabase();

    /* Apply --count-as before building features */
    if (!flagCountAs.empty()) setupCountAs(flagCountAs);

    /* Parse remap rules */
    std::vector<std::pair<std::string,std::string>> remapAllRules;
    for (auto& r : parseRemapRules(flagRemapAll)) remapAllRules.emplace_back(r.pattern, r.language);
    std::vector<std::pair<std::string,std::string>> remapUnknownRules;
    for (auto& r : parseRemapRules(flagRemapUnknown)) remapUnknownRules.emplace_back(r.pattern, r.language);

    if (flagLanguages) {
        fprintf(stdout, "%s", formatLanguages().c_str());
        return 0;
    }

    /* Pre-load all language features */
    languageFeatures.reserve(languageDatabase.size() * 2);
    for (auto& [name, lang] : languageDatabase) loadLanguageFeature(name);

    if (paths.empty()) paths.push_back(".");

    auto allowExts = splitCSV(flagAllowExt);
    auto excludeExts = splitCSV(flagExcludeExt);
    auto excludeFns = splitCSV(flagExcludeFile);

    /* Walk and collect jobs */
    std::vector<FileJob*> jobs;
    walkAndProcess(paths, excludeDirs, allowExts, excludeExts, excludeFns,
                   flagIncludeSymLinks, flagNoLarge,
                   flagLargeLineCount, flagLargeByteCount, jobs);

    if (jobs.empty()) {
        fprintf(stdout, "No files found to process\n");
        return 0;
    }

    int numWorkers = flagWorkers > 0 ? flagWorkers : (int)std::thread::hardware_concurrency();
    if (numWorkers < 1) numWorkers = 1;

    /* Process files in parallel */
    std::atomic<size_t> nextIdx{0};
    std::vector<std::thread> workers;
    CheckDuplicates dupChecker;
    std::mutex dupMutex;

    for (int t = 0; t < numWorkers; t++) {
        workers.emplace_back([&]() {
            while (true) {
                size_t idx = nextIdx.fetch_add(1);
                if (idx >= jobs.size()) break;

                FileJob* job = jobs[idx];
                job->content = readFileContent(
                    job->symlocation.empty() ? job->location : job->symlocation,
                    (int)job->bytes);

                if (job->content.empty()) { job->lines = 0; continue; }

                /* Remap-all check (runs before shebang detection) */
                if (!remapAllRules.empty()) hardRemapLanguage(job, remapAllRules, {});

                if (job->language == SheBang) {
                    if (!remapUnknownRules.empty()) hardRemapLanguage(job, {}, remapUnknownRules);
                    if (job->language == SheBang) {
                        std::string sb = detectSheBang(
                            std::string(reinterpret_cast<const char*>(job->content.data()),
                                        std::min(job->content.size(), (size_t)200)));
                        if (!sb.empty()) { job->language = sb; loadLanguageFeature(sb); }
                        else continue;
                    }
                }

                if (job->possibleLanguages.size() > 1)
                    job->language = determineLanguage(job->filename, job->language,
                                                       job->possibleLanguages, job->content);
                else if (job->possibleLanguages.size() == 1)
                    job->language = job->possibleLanguages[0];

                countStats(job, copts);

                /* Duplicate detection */
                if (flagNoDuplicates) {
                    uint64_t h = hashContent(job->content);
                    std::lock_guard<std::mutex> lock(dupMutex);
                    std::vector<uint8_t> hvec(sizeof(h));
                    memcpy(hvec.data(), &h, sizeof(h));
                    if (dupChecker.check(job->bytes, hvec)) { job->lines = -1; continue; }
                    dupChecker.add(job->bytes, hvec);
                }

                /* Skip minified/generated if requested */
                if (flagIgnoreMinified && job->minified) { job->lines = -1; continue; }
                if (flagIgnoreGenerated && job->generated) { job->lines = -1; continue; }

                /* Track ULOC globally */
                if (flagUloc) trackUloc(job);
            }
        });
    }
    for (auto& w : workers) w.join();

    /* Remove skipped jobs (duplicates, minified, generated) */
    jobs.erase(std::remove_if(jobs.begin(), jobs.end(), [](FileJob* j) {
        bool skip = j->lines < 0;
        if (skip) delete j;
        return skip;
    }), jobs.end());

    /* Build format options */
    FormatOptions fOpts;
    fOpts.byFile = flagByFile;
    fOpts.noComplexity = flagNoComplexity;
    fOpts.wide = flagMore;
    fOpts.ci = flagCi;
    fOpts.noHborder = flagNoHborder;
    fOpts.uloc = flagUloc;
    fOpts.dryness = flagDryness;
    fOpts.percent = flagPercent;
    fOpts.maxMean = flagMaxMean;
    fOpts.sortBy = flagSortBy;
    fOpts.formatName = flagFormat;
    fOpts.cocomo = !flagNoCocomo;
    fOpts.sloccountFormat = flagSloccountFormat;
    fOpts.locomo = flagLocomo || flagCostComparison;
    fOpts.costComparison = flagCostComparison;
    fOpts.noSize = flagNoSize;
    fOpts.projectType = flagCocomoProjectType;
    fOpts.currencySymbol = flagCurrencySymbol;
    fOpts.sizeUnit = flagSizeUnit;
    fOpts.averageWage = flagAverageWage;
    fOpts.overhead = flagOverhead;
    fOpts.eaf = flagEAF;
    fOpts.locomoPreset = flagLocomoPreset;
    fOpts.locomoInputPrice = flagLocomoInputPrice;
    fOpts.locomoOutputPrice = flagLocomoOutputPrice;
    fOpts.locomoTPS = flagLocomoTPS;
    fOpts.locomoInputPriceSet = flagLocomoInputPriceSet;
    fOpts.locomoOutputPriceSet = flagLocomoOutputPriceSet;
    fOpts.locomoTPSSet = flagLocomoTPSSet;
    fOpts.locomoCycles = flagLocomoCycles;
    fOpts.locomoCyclesSet = flagLocomoCyclesSet;
    fOpts.sqlProject = flagSQLProject;

    /* Format output - support --format-multi */
    if (!flagFormatMulti.empty()) {
        auto specs = splitCSV(flagFormatMulti);
        for (auto& spec : specs) {
            size_t colon = spec.find(':');
            std::string fmt = (colon == std::string::npos) ? spec : spec.substr(0, colon);
            std::string dest = (colon == std::string::npos) ? "stdout" : spec.substr(colon + 1);
            fOpts.formatName = fmt;
            std::string output = formatDispatch(fOpts, jobs);
            if (dest == "stdout") {
                fprintf(stdout, "%s\n", output.c_str());
            } else {
                FILE* f = fopen(dest.c_str(), "w");
                if (f) { fputs(output.c_str(), f); fclose(f); }
                else fprintf(stderr, "Could not write to %s\n", dest.c_str());
            }
        }
    } else {
        std::string output = formatDispatch(fOpts, jobs);
        if (flagOutput.empty()) {
            fprintf(stdout, "%s", output.c_str());
        } else {
            FILE* f = fopen(flagOutput.c_str(), "w");
            if (f) { fputs(output.c_str(), f); fclose(f); }
            else fprintf(stderr, "Could not write to %s\n", flagOutput.c_str());
        }
    }

    for (auto* j : jobs) delete j;
    return 0;
}
